# Generated by Django 2.1.7 on 2021-11-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211014_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='town',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='street',
            new_name='house_number',
        ),
    ]
