# Generated by Django 2.1.7 on 2021-11-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
